export const DriversActionTypes = {
  CURRENT_CONNECTED_DRIVER: "CURRENT_CONNECTED_DRIVER",
  REMOVE_ACTIVE_DRIVER: "REMOVE_ACTIVE_DRIVER",
  SET_ACTIVE_DRIVER_POSITION: "SET_ACTIVE_DRIVER_POSITION",
  CLEAR_ACTIVE_DRIVER: "CLEAR_ACTIVE_DRIVER",

  // when clicking the store show DRIVER_PANEL
  SHOW_DRIVER_PANEL: "SHOW_DRIVER_PANEL",
  // when clicking disconnect button SHOW_STORE_PANE
  SHOW_STORE_PANEL: "SHOW_STORE_PANEL",
};
export default DriversActionTypes;
