const DriversActionTypes = {
  ADD_ACTIVE_DRIVER: "ADD_ACTIVE_DRIVER",
  REMOVE_ACTIVE_DRIVER: "REMOVE_ACTIVE_DRIVER",
  SET_ACTIVE_DRIVER_POSITION: "SET_ACTIVE_DRIVER_POSITION",
  CLEAR_ACTIVE_DRIVER: "CLEAR_ACTIVE_DRIVER",
};
export default DriversActionTypes;
