const StoresActionTypes = {
  FETCH_API_STORE_LIST_USE_EFFECT: "FETCH_API_STORE_LIST_USE_EFFECT",
  PUT_STORES_IN_STATE: "PUT_STORES_IN_STATE",
  CONNECTED_STORE: "CONNECTED_STORE",
};
export default StoresActionTypes;
