const OrdersActionTypes = {
  // UI TYPES
  EXPAND_ORDER_DRAG_DROP_SIDEBAR: "EXPAND_ORDER_DRAG_DROP_SIDEBAR",
  COMPRESS_ORDER_DRAG_DROP_SIDEBAR: "COMPRESS_ORDER_DRAG_DROP_SIDEBAR",
  //DRAG DROP TYPES
  DELTA_DRIVER_FOR_DRAG_AND_DROP: "DELTA_DRIVER_FOR_DRAG_AND_DROP",

  REMOVE_DRIVER_FROM_DRAG_AND_DROP: "REMOVE_DRIVER_FROM_DRAG_AND_DROP",
  REMOVE_ORDER_FROM_DRIVER: "REMOVE_ORDER_FROM_DRIVER",
  SETUP_CURRENT_DRAG_DROP: "SETUP_CURRENT_DRAG_DROP",
  ADD_APIORDER_FAILURE_DRAG_DROP_TO_COLLECTION:
    "ADD_APIORDER_FAILURE_DRAG_DROP_TO_COLLECTION",
  PERSIST_ORDER_COLUMN: "PERSIST_ORDER_COLUMN",
  PERSIST_ALL_COLUMN: "PERSIST_ALL_COLUMN",

  SAVE_ORDER: "SAVE_ORDER",
  DISCARD_ORDER_CHANGES: "DISCARD_ORDER_CHANGES",
  //socket updates
  SOCKET_ORDER_NEW: "SOCKET_ORDER_NEW",
  SOCKET_ORDER_UPDATE: "SOCKET_ORDER_UPDATE",
  SOCKET_ORDER_DELETE: "SOCKET_ORDER_DELETE",
  SOCKET_ORDER_BUNDLES: "SOCKET_ORDER_BUNDLES",
  SOCKET_ORDER_SEND_UPDATE: "SOCKET_ORDER_SEND_UPDATE",
};
export default OrdersActionTypes;
